### ISSUE TITLE
Duvidas de uso

### ISSUE THREAD

**Issue by BenevidesLecontes** [vtex-apps/carousel#32]
Olá, estou desenvolvendo uma loja usando VTEX IO, quero usar o carousel, mas como vi que por baixo dos panos usa o slick carousel, eu queria poder passar custom react components por exemplo nas setas e poder customizar height dos items sem usar aquele enum 420 e 440, eu queria poder usar dimensões que quero. Tentei usar meu component carousel usando o react-slick, mas como não consigo pegar os banners usando a api Graphql eu fiquei sem como fazer. Alguém pode me dizer se há possibilidades dessa customização?

**Comment by BenevidesLecontes** [comment]
Obrigado pela resposta @salesfelipe e espero esse veredito. Mas há como eu ter acesso a api dos banners para que eu use meu próprio carousel? Eu estou limitado por essa questão queria uma solução provisória.

**Comment by salesfelipe** [comment]
Você pode criar seu própio carousel, basta copiar o getSchema do vtex-carousel e colocar nessa app. Então você vai poder editar o seu componente via editor, aka pages-editor, ele que acessa a api pra pegar as imagens relacionadas a aquele carousel.

**Comment by BenevidesLecontes** [comment]
@salesfelipe tentei fazer isso, mas ele dá bad request ao tentar acessar `vtex.pages-graphql`, tentei adicionar tal dependência, mas n tive sucesso. Pesquisei sobre e não encontro repositório algum sobre.

**Comment by salesfelipe** [comment]
@BenevidesLecontes como que tá o seu `manifest.json`?

**Comment by BenevidesLecontes** [comment]
@salesfelipe 
```
"dependencies": {
    "vtex.store-components": "1.x",
    "vtex.store-graphql": "2.x",
    "vtex.styleguide": "5.x",
    "vtex.carousel": "1.x"
  },
```

**Comment by brunojdo** [comment]
Ainda está com esse problema? @BenevidesLecontes 
A ideia é não permitirmos qualquer altura de banner, voce pode dizer qual a altura que gostaria?

**Comment by BenevidesLecontes** [comment]
@brunojdo eu consegui implementar banners customizados usando o schema do carousel como base e funcionava, mas a umas 3 semanas que isso já não funciona, pois o page-editor n funciona mais. Reportei lá no repo, mas ninguém responde. Eu estou parado e não consigo desenvolver nada que dependa do page-editor

**Comment by brunojdo** [comment]
Ok. Vou responder lá. A app agora se chama `vtex.admin-pages`.
