### ISSUE TITLE
Missing Namespaces from Component

### ISSUE THREAD

**Issue by jpgutti** [vtex-apps/carousel#56]
## Expected Behavior
It should have some namespaces like ".arrow", ".arrowRight", ".arrowLeft", but those has vanished from carousel component.

## Current Behavior
After last releases, some namespaces have vanished from component, breaking down some styles.

## Possible Solution
I suggest a re-check in last releases to see what is happening, or if this is known by you, update README.md the namespaces removed.

## Steps to Reproduce (for bugs)
1. Clone store-theme into the project folder and reach vtex carousel component trying to see namespaces like ".arrow", "rightArrow" and ".leftArrow"

## Context
The issue has broken down some styles from our stores projects, we just need to understand if this is a bug or a definitive release to work around.

**Comment by Klynger** [comment]
Hi, those labels had there names changed, `arrow` continues the same, but `arrowRight` is now `rightArrow` and `arrowLeft` is now `leftArrow`. There is a [section](https://github.com/vtex-apps/carousel#styles-api) in the README talking about this, but the table isn't displaying very well, gonna fix it now.

**Comment by Klynger** [comment]
I talked with some guys here, and we think that is better to change back to `arrowLeft` and `arrowRight`

**Comment by jpgutti** [comment]
Great! Thanks for that...

We're gonna wait for the next release then!
