### ISSUE TITLE
Add heading and subheading to a banner

### ISSUE THREAD

**Issue by lucasayb** [vtex-apps/carousel#71]
I'm working with a store that needs to have a slider with texts inside it. I would like to have the possibility of editing the banner images and it's texts inside it.

The ideal approach of this feature would be to edit each banner information, as we have today with the properly attributes, and also add an heading, subheading and a call to action to each image that is being displayed in the carousel.

**Comment by hapoza** [comment]
+1 to that, I came here to create the exact same issue :smile:.

One possible solution would be aloowing the use of info-card block inside of carousel, because the info-card alreay has all the features we need.

**Comment by denisebiscaro** [comment]
We'll work on the solution of adding the possibility to create a carousel of infocards as @hapoza suggested. It will be available in late July.

**Comment by victorhmp** [comment]
This is solved by `vtex.slider-layout` :)
