### ISSUE TITLE
Create A Brand Slider

### ISSUE THREAD

**Issue by crodriguez85** [vtex-apps/carousel#75]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dhirama** [comment]
@crodriguez85 
Doesn't vtex.slider do the trick?
https://github.com/vtex-apps/slider

**Comment by victorhmp** [comment]
This is supported by `vtex.slider-layout`.
