### ISSUE TITLE
 Add a new property for the carousel component schema

### ISSUE THREAD

**Issue by Erislandio** [vtex-apps/carousel#93]
I am working for some clients and noticed the lack of a tablet size image, would it be possible to open a pull request for this at the moment?

## Expected Behavior

Banner for tablet devices

## Current Behavior
we have the option of mobile and desktop banner only

## Possible Solution
Add a new property for the carousel component schema
https://github.com/vtex-apps/carousel/blob/master/react/Carousel.tsx#L229

**Comment by victorhmp** [comment]
Solved by #94
